export const data = [
  {
    id: '12',
    name: 'Alexander',
    status: 'Dead',
    species: 'Human',
    gender: 'Male',
  },
  {
    id: '13',
    name: 'Alien Googah',
    status: 'unknown',
    species: 'Alien',
    gender: 'unknown',
  },
  {
    id: '6',
    name: 'Abadango Cluster Princess',
    status: 'Alive',
    species: 'Alien',
    gender: 'Female',
  },
  {
    id: '8',
    name: 'Adjudicator Rick',
    status: 'Dead',
    species: 'Human',
    gender: 'Male', 
  },
  {
    id: '34',
    name: 'Benjamin',
    status: 'Alive',
    species: 'Poopybutthole',
    gender: 'Male', 
  },
  {
    id: '148',
    name: 'Goddess Beth',
    status: 'unknown',
    species: 'Mytholog',
    gender: 'Female', 
  },
  {
    id: '41',
    name: 'Big Boobed Waitress',
    status: 'Alive',
    species: 'Humanoid',
    gender: 'Female', 
  },
];
